# Generated by Django 3.2.12 on 2022-03-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(max_length=250)),
                ('receiver_email', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=250)),
                ('chat_body', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
